### ISSUE TITLE
Panic while creating keyspace with next code base

### ISSUE THREAD

**Issue by SergioArrighi** [skytable/client-rust#22]
Hello all,

code base: next

**I'm using a pool in a struct then I init connectivity**
let sky_manager = ConnectionManager::new_notls(
        dotenv!("DB_HOST"),
        dotenv!("DB_PORT").parse::<u16>().unwrap(),
    );
    let sky_pool = AsyncPool::builder()
        .max_size(10)
        .build(sky_manager)
        .await
        .unwrap();
    let mut db_provider = PoolProvider::<SkyProvider>::new(SkyProvider::new(sky_pool));
    db_provider.inner.init().await;
    
 **In init method I use:**
 let mut connection = self.pool.get().await.unwrap();
        let initialized = !connection
            .create_keyspace("admin")
            .await
            .unwrap();
            
 Something in this instruction breaks when switching to git current version
 skytable = { git = "https://github.com/skytable/client-rust.git", features=["aio"], default-features = false }
And skytable version v0.8.0.
It works just fine with previous version.
            
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SkyError(UnexpectedResponse)', src/skytable.rs:95:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/result.rs:1750:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/result.rs:1090:23
   4: <advanced_sync::skytable::SkyProvider as advanced_sync::skytable::DbProvider>::init::{{closure}}
             at ./src/skytable.rs:92:28
   5: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/future/future.rs:125:9
   6: advanced_sync::main::{{closure}}
             at ./src/main.rs:69:29
   7: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /Users/sergioarrighi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.1/src/runtime/park.rs:283:63
   8: tokio::runtime::coop::with_budget
             at /Users/sergioarrighi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.1/src/runtime/coop.rs:107:5
   9: tokio::runtime::coop::budget
             at /Users/sergioarrighi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.1/src/runtime/coop.rs:73:5
  10: tokio::runtime::park::CachedParkThread::block_on
             at /Users/sergioarrighi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.1/src/runtime/park.rs:283:31
  11: tokio::runtime::context::BlockingRegionGuard::block_on
             at /Users/sergioarrighi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.1/src/runtime/context.rs:315:13
  12: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /Users/sergioarrighi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.1/src/runtime/scheduler/multi_thread/mod.rs:66:9
  13: tokio::runtime::runtime::Runtime::block_on
             at /Users/sergioarrighi/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.28.1/src/runtime/runtime.rs:304:45
  14: advanced_sync::main
             at ./src/main.rs:164:5
  15: core::ops::function::FnOnce::call_once
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:250:5
             
 Thanks and best regards

**Comment by ohsayan** [comment]
This is because of a protocol mismatch. Please upgrade to the latest Skytable release and client driver :)
