### ISSUE TITLE
ParseError(ResponseMismatch) when querying binary data

### ISSUE THREAD

**Issue by rubenjr0** [skytable/client-rust#25]
I've ran into an issue: I have a model with these fields:
- bin1: binary
- bin2: binary
- mystring: string

When I run `select bin1 from myspace.mymodel where id = something` on skysh, I get the desired output, the binary data of field bin1. If I ran `select bin1, bin2 ...` it would work as well.

On the rust client, I need to get bin1 and mystring together, and b3 separatedly, so I created a struct:
```rust
struct Pack {
    bin1: Vec<u8>,
    mystring: String
}
```

I then can do something like `let pack: Pack = db.query_parse(...).unwrap()` and it would work.

However, if I do `let bin3: Vec<u8> = db.query_parse(...).unwrap()` it returns `ParseError(ResponseMismatch)`. Creating a struct that holds `bin3: Vec<u8>` doesn't work either.

I have found this workaround:
```rust
let res = db.query(...).unwrap();
let bin3: Vec<u8> = match res {
    Response::Row(row) => row.into_first_as().unwrap(),
    _ => panic!("not what I expected")
};
```

I was wondering if I'm doing something wrong, or if there's a bug, in which case I'd be happy to take a look and help.

**Comment by ohsayan** [comment]
Hi! The error is expected because when you use `query_parse::<Type>()` with a `Type` which is a [`Value`](https://docs.rs/skytable/0.8.3/skytable/response/enum.Value.html), the method is trying to get the `Type` from a [`Response::Value`](https://docs.rs/skytable/0.8.3/skytable/response/enum.Response.html#variant.Value) which it isn't.

The recommended way to get a single item from a row directly is this:
```rust
let mybin: (Vec<u8>,) = db.query_parse(...).unwrap();
```

As for your struct, you can try using the derive macros [`Query`](https://docs.rs/skytable/0.8.3/skytable/derive.Query.html) and [`Response`](https://docs.rs/skytable/0.8.3/skytable/derive.Response.html) ([see an example here](https://github.com/skytable/client-rust#definitive-example)).

**Comment by ohsayan** [comment]
Note that the `,` in `(Vec<u8>, )` is important because that's what makes it a tuple (row)!

**Comment by rubenjr0** [comment]
Oh that makes so much sense! Using `let (mybin,): (Vec<u8>,) = ...` worked perfectly.

I was using the derive macros as suggested in the example, but that still caused an error with the struct with a single field. 

I've tried querying and parsing other fields in my model using a struct with a single field, and those cases resulted in an error too. Example:

```rust
#[derive(Query, Response)]
pub struct GetName {
    pub name: String,
}

let name_struct: GetName = db.query_parse(&query!(
        "select name from myspace.users where id = ?", 
        user_id)
    )
    .expect("Error getting name");
```
`Error getting name: ParseError(ResponseMismatch)`

Since having a struct to retrieve a single field seems overkill to me I will stick to `let myvar: (Type,)` anyway, but I wanted to make sure if using structs with the derive macros that way (single field) was okay.

Thanks!

**Comment by ohsayan** [comment]
@rubenjr0 You've actually found a bug with the derive macro. I've just released a new version `0.8.4` with the fix. Please try it out and let me know if it works as expected.

**Comment by ohsayan** [comment]
@rubenjr0 You've actually found a bug with the derive macro. I've just released a new version 0.8.5 with the fix. Please try it out and let me know if it works as expected.

**Comment by rubenjr0** [comment]
I will try it out and post an update as soon as possible. Thank you.

**Comment by rubenjr0** [comment]
@ohsayan Works perfectly, structs with a single field are being parsed correctly.

**Comment by ohsayan** [comment]
Great! I'm closing this issue for now. Please re-open if you have any other issues \:)
