### ISSUE TITLE
Add byte array to Query

### ISSUE THREAD

**Issue by martinmolin** [skytable/client-rust#5]
Currently `Query::arg` exists in order to add a `String` to a `Query`, this works really well with something like **serde_json**. However, it would be really convenient to also be able to add a `Vec<u8>` or similar directly to a `Query` in order to store a binary blob using something like **bincode** to serialize the data.

**Comment by ohsayan** [comment]
Blocking on skytable/skytable#157

**Comment by ohsayan** [comment]
Way to go, this has been implemented!
